server:
  port: 8080
  servlet:
    context-path: /

spring:
  #静态资源处理
  web:
    resources:
      # 启动默认静态资源处理, 默认启用
      add-mappings: true
      cache:
        #缓存相应时间, 单位秒
        cachecontrol:
          max-age: 3600
      chain:
        # 资源链启动缓存, 默认启动
        cache: true
        # 启用资源链, 默认禁用
        enabled: true
        # 启用压缩资源(gzip, brotli)解析, 默认禁用
        compressed: true
      static-locations: classpath:/static/

  application:
    name: seckill

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: zhenxun
    password: zhenxun123456
    hikari:
      pool-name: DateHikariCP # 连接池名
      minimum-idle: 5 # 最小空闲连接出
      idle-timeout: 1800000 # 空闲连接存活最大时间, 默认600000(10分钟)
      maximum-pool-size: 10 # 最大连接数, 默认10
      auto-commit: true # 从连接池返回的连接自动提交
      max-lifetime: 1800000 # 连接最大存活时间, 0表示永久存活, 默认1800000(30分支)
      connection-timeout: 30000 # 连接超时时间, 默认30000(30秒)
      connection-test-query:  SELECT 1 # 测试连接是否可用的查询语句

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8 # 最大连接数
          max-wait: 10000ms # 最大连接阻塞等待时间
          max-idle: 200 # 最大空闲连接
          min-idle: 5 # 最小空闲连接

  # RabbitMQ
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费这最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息, 处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器, 默认为true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true

    template:
      retry:
        # 发布重试, 默认为false
        enabled: true
        # 重试时间, 默认1000ms
        initial-interval: 1000ms
        # 重试最大次数, 默认三次
        max-attempts: 3
        # 最大间隔时间, 默认10000ms
        max-interval: 10000ms
        # 重试的间隔系数, eg: 系数为2, 第一次等待10s, 则第二次等待20s, 第三次等待40s
        multiplier: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml # 配置Mapper.xml映射文件
  type-aliases-package: com.dong.seckill.pojo # 配置mybatis数据返回类型别名

# mybatis SQL打印(方法接口所在的包, 不是Mapper.xml所在的包)
logging:
  level:
    com.dong.seckill.mapper: debug